### ISSUE TITLE
Error when running with google colab AttributeError: 'str' object has no attribute 'device

### ISSUE THREAD

**Issue by G-force78** [another-ai/stable_cascade_easy#5]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 489, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "/content/stable_cascade_easy/app.py", line 27, in image_print_create
    prior_output = prior(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/stable_cascade/pipeline_stable_cascade_prior.py", line 579, in __call__
    predicted_image_embedding = self.prior(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/stable_cascade/modeling_stable_cascade_common.py", line 298, in forward
    for c in self.t_conds:
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/stable_cascade/modeling_stable_cascade_common.py", line 223, in gen_r_embedding
    device = torch.device("cuda:0")  # create a PyTorch device object
AttributeError: 'str' object has no attribute 'device'

**Comment by rikkar69** [comment]
I found a workaround for the issue in the official cascade repo. 

Uninstall diffusers: `pip uninstall diffusers `

Install an earlier commit: `pip install git+https://github.com/kashif/diffusers.git@a3dc21385b7386beb3dab3a9845962ede6765887`

https://github.com/Stability-AI/StableCascade/issues/45
